project:
  type: website

website:
  title: "Project PariVo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Project Status
        menu:
        - text: Project Parivo Project

        - text: System Overview & Documentation 
          href: currentStatus/systemOverview.qmd

        - text: FPGA Design
          href: currentStatus/fpgaDesign.qmd

        - text: MCU Design
          href: currentStatus/mcuDesign.qmd

        - text: FPGA and MCU Communication
          href: currentStatus/fpgaToMcu.qmd

        - text: Results & Analysis of System
          href: currentStatus/resultsAndAnalysis.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



